# Theming
font: Victor Mono Bold Italic 14
background: "#282828d0"
color: "#fbf1c7"
border: "#FB4934"
separator: " â–¶ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

# namespace to use for the layer shell surface
#namespace: "wlr_which_key"

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "a"
    desc: Action
    submenu:
      - key: "r"
        desc: Runner
        cmd: |
          rofi -show combi -modes "combi,drun,run" -combi-modi "drun,run" -theme-str 'configuration { font: "Victor Mono Bold Italic 15"; display-combi: "cmd"; } * { bg0: #272E33; fg0: #D3C6AA; accent: #E69875; } window { background-color: @bg0; } mainbox { children: [inputbar, listview]; } inputbar { background-color: @bg0; children: [prompt, entry]; padding: 5px; } prompt { background-color: @bg0; text-color: @accent; margin: 0 15px 0 0; } entry { background-color: @bg0; text-color: @fg0; } listview { background-color: @bg0; lines: 12; } element { padding: 4px; background-color: @bg0; text-color: @fg0; } element selected { background-color: @accent; text-color: @bg0; }'
      - key: "h"
        desc: Clipboard history
        cmd: cliphist list | wmenu -l 10 | cliphist decode | wl-copy
      - key: "s"
        desc: Screenshot
        submenu:
          - key: "s"
            desc: Current Monitor
            cmd: nirishot
          - key: "r"
            desc: Region
            cmd: nirishot region
          - key: "e"
            desc: Edit
            cmd: nirishot edit
      - key: "k"
        desc: Close Window
        cmd: niri msg action close-window
      - key: "g"
        desc: Gif
        submenu:
          - key: "g"
            desc: Current Monitor
            cmd: regif 8
          - key: "r"
            desc: Region
            cmd: regif region 8

  - key: "e"
    desc: Exec
    submenu:
      - key: "w"
        desc: Windows
        cmd: nirigo.py
      - key: "v"
        desc: AnkiVim
        cmd: ankivim.sh
      - key: "g"
        desc: Search
        cmd: searchon
      - key: "t"
        desc: Grab Text (Enhanced)
        cmd: grab-text
      - key: "d"
        desc: Drag 
        cmd: imdrag /home/digo/Downloads /home/digo/.pictures /home/digo/.wallpapers
      - key: "u"
        desc: Utilities for some apps
        submenu:
            - key: "l"
              desc: Set LSFG for process
              cmd: vkpick

  - key: "s"
    desc: Scratchpads
    submenu:
      - key: "u"
        desc: Dropdown
        cmd: nscratch.py -id dropdown -m -a || alacritty -o window.opacity=0.7 --class dropdown --title dropdown
      - key: "c"
        desc: Calculator
        cmd: nscratch.py -id calculator -m -a || foot -a calculator -T calculator -e python3 -q
      - key: "i"
        desc: AI
        cmd: nscratch.py -id IA -m -a || foot -a IA -T IA -e aichat -r quick-res
      - key: "t"
        desc: Todo
        cmd: nscratch.py -id Kuro -m -a || kuro
      - key: "b"
        desc: Monitor
        cmd: nscratch.py -id monitor -m -a || foot -a monitor -T monitor -e btop 
      - key: "n"
        desc: Notes
        cmd: nscratch.py -id notes -m -a || foot -a notes -T notes -e vim ~/.vimwiki/index.md
      - key: "h"
        desc: Habits
        cmd: nscratch.py -id habits -m -a || foot -a notes -T habits -e nvim ~/.notes/habits.norg 
