# Theming
font: JetBrainsMono Nerd Font 12
background: "#282828d0"
color: "#fbf1c7"
border: "#8ec07c"
separator: " âžœ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

# namespace to use for the layer shell surface
#namespace: "wlr_which_key"

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "a"
    desc: Action
    submenu:
      - key: "s"
        desc: Screenshot
        submenu:
          - key: "s"
            desc: Current Monitor
            cmd: flashy
          - key: "r"
            desc: Region
            cmd: flashy region
          - key: "z"
            desc: Zoom
            cmd: flashy zoom
      - key: "k"
        desc: Close Window
        cmd: niri msg action close-window
      - key: "g"
        desc: Gif
        submenu:
          - key: "g"
            desc: Current Monitor
            cmd: regif 8
          - key: "r"
            desc: Region
            cmd: regif region 8

  - key: "e"
    desc: Exec
    submenu:
      - key: "r"
        desc: Runner
        cmd: wmenu-run -f 'Martian Mono Nerd Font 15'  -N '#272E33' -n '#D3C6AA' -S '#272E33' -s '#E69875'
      - key: "w"
        desc: Windows
        cmd: nirigo.py
      - key: "d"
        desc: Drag 
        cmd: imdrag /home/digo/Downloads /home/digo/.pictures /home/digo/.wallpapers

  - key: "s"
    desc: Scratchpads
    submenu:
      - key: "u"
        desc: dropdown
        cmd: nscratch.py -id dropdown -m -a || foot -a dropdown -T dropdown
      - key: "c"
        desc: calculator
        cmd: nscratch.py -id calculator -m -a || foot -a calculator -T calculator -e python -q
      - key: "t"
        desc: Todo
        cmd: nscratch.py -id todo -m -a || foot -a todo -T todo -e taskwarrior-tui
      - key: "b"
        desc: monitor
        cmd: nscratch.py -id monitor -m -a || foot -a monitor -T monitor -e btop 
      - key: "n"
        desc: notes
        cmd: nscratch.py -id notes -m -a || foot -a notes -T notes -e nvim ~/.notes/index.norg 
      - key: "h"
        desc: habits
        cmd: nscratch.py -id habits -m -a || foot -a notes -T habits -e nvim ~/.notes/habits.norg 
