general.import = ["~/.config/alacritty/nord.toml"]
[env]
term = "alacritty"

[font]
size = 12.0

[font.bold]
family = "Victor Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Victor Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Victor Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Victor Mono Nerd Font"
style = "Bold"

[window]
opacity = 1.0

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "C", mods = "Control|Alt", action = "ToggleViMode" },
]

[cursor]
style = { blinking="Always" }
